import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en' id='root'>
			<body className={`${inter.className} `}>
				{/* <Header bg='bg-orange-500' />
				<Header bg='bg-green-500' />
				<Header bg='bg-blue-500' /> */}
				<Header />

				<main className='p-20'>{children}</main>
			</body>
		</html>
	);
}
